# Generated by Django 2.2.4 on 2019-11-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyc', '0003_remove_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-body']},
        ),
    ]
